name: '⚡ Feature Request'
description: 'Suggest a feature for AkjoNav!'
title: '[Feature Request] <title>'
labels:
  - 'status: none'
  - 'type: feature'

body:
  - type: dropdown
    id: module
    attributes:
      label: 'Which module would you like to request a feature for?'
      options:
        - AkjoNav-Model
        - AkjoNav-Base
        - AkjoNav-Routing
        - AkjoNav-MapServer
        - AkjoNav-TileServer
        - AkjoNav-Web
        - AkjoNav-Mobile
        - AkjoNav-WebMapper
        - AkjoNav-DesktopMapper
        - AkjoNav-OsmConverter
      multiple: false
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 'Problem Description'
      description: 'Is your feature request related to a problem? Please describe.'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 'Solution Description'
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives'
      description: 'A clear and concise description of any alternative solutions or features you have considered.'
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 'Additional Context'
      description: 'Add any other context or screenshots about the feature request here.'
      value: 'No additional context/screenshots.'
    validations:
      required: false
