name: '⚠ Security Vulnerability'
description: 'Report a security vulnerability in AkjoNav!'
title: '[Security Vulnerability] <title>'
labels:
  - 'status: none'
  - 'type: vulnerability'

body:
  - type: dropdown
    id: module
    attributes:
      label: 'Which module would you like to request documentation for?'
      options:
        - AkjoNav-Model
        - AkjoNav-Base
        - AkjoNav-Routing
        - AkjoNav-MapServer
        - AkjoNav-TileServer
        - AkjoNav-Web
        - AkjoNav-Mobile
        - AkjoNav-WebMapper
        - AkjoNav-DeskoptMapper
        - AkjoNav-OsmConverter
      multiple: false
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: 'Version'
      description: 'What version of AkjoNav is the bug in?'
      value: 'v2022.1-dev1'
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: 'Contact'
      description: 'Tell us your e-mail or a the email of a person that can be contacted for more information.'
      value: 'Email: '
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 'Additional Information'
      description: 'Add any other information you want to provide.'
      value: 'No additional information given.'
    validations:
      required: false