name: '📖 Documentation'
description: 'Suggest either new documentation or changes to existing documentation.'
title: '[Documentation] <title>'
labels:
  - 'status: none'
  - 'type: documentation'

body:
  - type: dropdown
    id: module
    attributes:
      label: 'Which module would you like to request documentation for?'
      options:
        - AkjoNav-Model
        - AkjoNav-Base
        - AkjoNav-Routing
        - AkjoNav-MapServer
        - AkjoNav-TileServer
        - AkjoNav-Web
        - AkjoNav-Mobile
        - AkjoNav-WebMapper
        - AkjoNav-DeskoptMapper
        - AkjoNav-OsmConverter
      multiple: false
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: 'Version'
      description: 'The version of AkjoNav the documentation is for, if applicable.'
    validations:
      required: false

  - type: input
    id: language
    attributes:
      label: 'Language'
      description: 'The language of the documentation, if applicable.'
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: 'URL'
      description: 'The URL to the documentation, if applicable.'
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'A clear and concise description of what you want to happen.'
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 'Additional Context'
      description: 'Add any other context or screenshots of the documentation here.'
      value: 'No additional context/screenshots.'
    validations:
      required: false