name: '⁉ Other Request/Issue'
description: 'Any other request or issue you have for AkjoNav that cannot be addressed in the other categories.'
title: '[Other] <title>'
labels:
  - 'status: none'
  - 'type: other'

body:
  - type: textarea
    id: request
    attributes:
      label: 'Request'
      description: 'What is your request/issue?'
    validations:
      required: true